version: '3.9'

services:
  traefik:
    image: traefik:latest
    container_name: traefik
    ports:
      - 80:80
      - 443:443
      - 8080:8080
    networks:
      - proxy
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
      - ./traefik:/etc/traefik

  web1:
    image: nginx:latest
    container_name: web1
    networks:
      - proxy
    ports:
      - 81:80
    volumes:
      - ./nginx/html/index1.html:/usr/share/nginx/html/index.html  # Mount HTML files
    restart: always  


  web2:
    image: nginx:latest
    container_name: web2
    networks:
      - proxy
    ports:
      - 82:80
    volumes:
      - ./nginx/html/index2.html:/usr/share/nginx/html/index.html  # Mount HTML files
    restart: always
  
  web3:
    image: nginx:latest
    container_name: web3
    networks:
      - proxy
    ports:
      - 83:80
    volumes:
      - ./nginx/html/index3.html:/usr/share/nginx/html/index.html  # Mount HTML files
    restart: always
    
networks:
  proxy:
    name: proxy

volumes:
  letsencrypt:
    name: letsencrypt