version: '3.9'

services:
  traefik:
    image: traefik:v2.5
    container_name: traefik
    ports:
      - 80:80
      - 443:443
    networks:
      - proxy
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
      - ./letsencrypt:/letsencrypt
      - ./traefik/traefik.yml:/etc/traefik/traefik.yml
      - ./traefik/dynamic:/etc/traefik/dynamic
    command:
      - --api.insecure=true
      - --providers.docker
      - --entrypoints.web.address=:80
      - --entrypoints.websecure.address=:443
      - --certificatesresolvers.myresolver.acme.email=marcelo.gdomingues@outlook.com
      - --certificatesresolvers.myresolver.acme.storage=/letsencrypt/acme.json
      - --certificatesresolvers.myresolver.acme.tlschallenge=true
    labels:
      - traefik.enable=true
      - traefik.http.routers.mydashboard.rule=Host(`traefik.example.com`)
      - traefik.http.routers.mydashboard.service=api@internal

  web1:
    image: nginx
    container_name: web1
    networks:
      - proxy
    ports:
      - 81:80
    volumes:
      - ./nginx/html:/usr/share/nginx/html  # Mount HTML files
      - ./nginx/conf/web1.conf:/etc/nginx/conf.d/default.conf  # Mount Nginx configuration
    restart: always  
    labels:
      - traefik.enable=true
      - traefik.http.routers.web1.rule=Host(`web1.example.com`)
      - traefik.http.services.web1.loadbalancer.server.port=80

  web2:
    image: nginx
    container_name: web2
    networks:
      - proxy
    ports:
      - 82:80
    volumes:
      - ./nginx/html:/usr/share/nginx/html  # Mount HTML files
      - ./nginx/conf/web2.conf:/etc/nginx/conf.d/default.conf  # Mount Nginx configuration
    restart: always
    labels:
      - traefik.enable=true
      - traefik.http.routers.web2.rule=Host(`web2.example.com`)
      - traefik.http.services.web2.loadbalancer.server.port=80

  web3:
    image: nginx
    container_name: web3
    networks:
      - proxy
    ports:
      - 83:80
    volumes:
      - ./nginx/html:/usr/share/nginx/html  # Mount HTML files
      - ./nginx/conf/web3.conf:/etc/nginx/conf.d/default.conf  # Mount Nginx configuration
    restart: always
    labels:
      - traefik.enable=true
      - traefik.http.routers.web3.rule=Host(`web3.example.com`)
      - traefik.http.services.web3.loadbalancer.server.port=80
    
networks:
  proxy:
    name: proxy

volumes:
  letsencrypt:
    name: letsencrypt