http:
  routers:
    ulhtoms:
      rule: "Host(`ulhtoms.com`)"
      entryPoints: web
      service: ulhtoms-cluster

  services:
    ulhtoms-cluster:
      loadBalancer:
        servers:
          - url: "http://web1.example.com"
          - url: "http://web2.example.com"
          - url: "http://web3.example.com"
