http:
  routers:
    ulhtoms:
      rule: "Host(`www.ulhtoms.com`)"
      entryPoints: web
      service: ulhtoms-cluster

  services:
    ulhtoms-cluster:
      loadBalancer:
        servers:
          - url: "http://192.168.1.238:81"
          - url: "http://192.168.1.238:82"
          - url: "http://192.168.1.238:83"