http:
  routers:
    ulhtoms:
      rule: "Host(`www.ulhtoms.com`)"
      entryPoints: web
      service: ulhtoms-cluster

  services:
    ulhtoms-cluster:
      loadBalancer:
        servers:
          - url: "http://172.19.0.2:80"
          - url: "http://172.19.0.5:80"
          - url: "http://172.19.0.3:80"